export const getUsers = (req, res, next) => {
  try {
    
  } catch (error) {
    next(error);
  }
};
